services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf